language: perl
install: cpanm --quiet --installdeps --with-develop --notest .
perl:
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.18-shrplib"
    - "5.20"
    - "5.20-shrplib"
    - "5.22"
    - "5.22-shrplib"
    - "5.24"
    - "5.24-shrplib"
    - "5.26"
